#!.venv/bin/python

import unittest

if __name__ == "__main__":
    suite = unittest.TestLoader().discover('tests')
    teste = unittest.TextTestRunner(verbosity=2).run(suite)

    if len(teste.failures) > 0:
        raise TypeError("Erro ao executar os testes!")